# -*- coding: utf-8 -*-
"""词库：附录 A 全量（80 词 / 10 类 / 每类 8 词）。

每条含 word / pos / hint / difficulty。原样移植，供 engine.draw_from_bank 使用。
"""

WORD_BANK = {
    "水果": [
        {"word": "西瓜", "pos": "名词", "hint": "夏天冰镇后最治愈，绿皮裹红瓤、籽被随手吐掉", "difficulty": "简单"},
        {"word": "葡萄", "pos": "名词", "hint": "藤上成串垂挂，鲜食或酿成紫色琼浆", "difficulty": "简单"},
        {"word": "榴莲", "pos": "名词", "hint": "气味劝退却拥趸狂热的热带果王，浑身是刺", "difficulty": "中等"},
        {"word": "芒果", "pos": "名词", "hint": "黄澄澄的甜果，核边总缠着一缕纤维", "difficulty": "中等"},
        {"word": "草莓", "pos": "名词", "hint": "红心小白点，奶油最配的酸甜味", "difficulty": "中等"},
        {"word": "樱桃", "pos": "名词", "hint": "小小一颗红玛瑙，常成双成对着", "difficulty": "中等"},
        {"word": "桃子", "pos": "名词", "hint": "绒毛外皮裹蜜肉，猴哥最爱", "difficulty": "困难"},
        {"word": "柠檬", "pos": "名词", "hint": "酸到皱眉的黄皮果，泡水去腻", "difficulty": "困难"},
    ],
    "动物": [
        {"word": "熊猫", "pos": "名词", "hint": "黑白配色、以竹为食的中国名片", "difficulty": "简单"},
        {"word": "老虎", "pos": "名词", "hint": "橙底黑纹的林中大猫，一声吼镇山", "difficulty": "简单"},
        {"word": "考拉", "pos": "名词", "hint": "整天抱树打盹的澳洲土著，靠桉叶续命", "difficulty": "中等"},
        {"word": "企鹅", "pos": "名词", "hint": "南极的小老头，翅膀退化成划水桨", "difficulty": "简单"},
        {"word": "鲸鱼", "pos": "名词", "hint": "海里最大的哺乳动物，换气喷起高高的水柱", "difficulty": "中等"},
        {"word": "蜥蜴", "pos": "名词", "hint": "断尾能逃生的爬行高手，皮肤随环境变", "difficulty": "困难"},
        {"word": "刺猬", "pos": "名词", "hint": "一受惊就团成球，满身尖刺的小兽", "difficulty": "困难"},
        {"word": "海豚", "pos": "名词", "hint": "海里高智商的精灵，跃出水面顶球", "difficulty": "中等"},
    ],
    "美食": [
        {"word": "火锅", "pos": "名词", "hint": "一群人围着翻滚汤底边涮边聊", "difficulty": "中等"},
        {"word": "汤包", "pos": "名词", "hint": "薄皮一咬，滚烫汤汁先涌出来", "difficulty": "中等"},
        {"word": "米粉", "pos": "名词", "hint": "细长雪白，柳州那碗酸臭上头", "difficulty": "中等"},
        {"word": "煎饼", "pos": "名词", "hint": "摊薄脆刷酱卷葱花的街头早餐", "difficulty": "中等"},
        {"word": "烤鸭", "pos": "名词", "hint": "果木熏烤，片皮蘸甜酱裹薄饼", "difficulty": "困难"},
        {"word": "豆腐", "pos": "名词", "hint": "白嫩一块，麻婆手里又麻又辣", "difficulty": "中等"},
        {"word": "烧烤", "pos": "名词", "hint": "夜市烟火里，串串翻转滋滋冒油", "difficulty": "中等"},
        {"word": "拉面", "pos": "名词", "hint": "师傅空中甩面，越拉越长", "difficulty": "困难"},
    ],
    "地名": [
        {"word": "北京", "pos": "名词", "hint": "故宫长城坐落其间的千年帝都", "difficulty": "简单"},
        {"word": "上海", "pos": "名词", "hint": "外滩钟声与东方明珠辉映的摩登港城", "difficulty": "简单"},
        {"word": "重庆", "pos": "名词", "hint": "8D魔幻山城，轻轨穿楼而过", "difficulty": "中等"},
        {"word": "三亚", "pos": "名词", "hint": "椰风海浪的度假代名词", "difficulty": "中等"},
        {"word": "拉萨", "pos": "名词", "hint": "日光城，布达拉宫矗立的高原圣城", "difficulty": "中等"},
        {"word": "丽江", "pos": "名词", "hint": "纳西古城，酒吧与流水交织的文艺小镇", "difficulty": "中等"},
        {"word": "漠河", "pos": "名词", "hint": "中国版图最北端，冬夜可追极光", "difficulty": "困难"},
        {"word": "喀什", "pos": "名词", "hint": "丝路尽头的新疆古城，巴扎烟火气十足", "difficulty": "困难"},
    ],
    "动漫角色": [
        {"word": "悟空", "pos": "名词", "hint": "金箍棒在手，一个筋斗十万八千里", "difficulty": "中等"},
        {"word": "路飞", "pos": "名词", "hint": "橡胶人，草帽下藏着成为海贼王的梦", "difficulty": "中等"},
        {"word": "鸣人", "pos": "名词", "hint": "脸上有螺旋标记，嘴里总喊我相信你", "difficulty": "中等"},
        {"word": "哪吒", "pos": "名词", "hint": "脚踏风火轮，混天绫翻飞", "difficulty": "中等"},
        {"word": "超人", "pos": "名词", "hint": "红披风胸前S，飞天救人的外星之子", "difficulty": "中等"},
        {"word": "蝙蝠", "pos": "名词", "hint": "黑衣披风，哥谭夜里惩恶的富豪", "difficulty": "中等"},
        {"word": "葫芦", "pos": "名词", "hint": "七个本领各异的兄弟，下山救爷爷", "difficulty": "简单"},
        {"word": "蜘蛛", "pos": "名词", "hint": "纽约高楼间吐丝荡悠的青年", "difficulty": "中等"},
    ],
    "影视": [
        {"word": "地球", "pos": "名词", "hint": "人类给家园装发动机，推着去流浪", "difficulty": "中等"},
        {"word": "复仇", "pos": "名词", "hint": "各路超级英雄组队打团", "difficulty": "中等"},
        {"word": "泰坦", "pos": "名词", "hint": "冰海沉船，生死相随的爱情", "difficulty": "中等"},
        {"word": "千寻", "pos": "名词", "hint": "误入神灵世界的少女，名字被悄然夺走", "difficulty": "中等"},
        {"word": "卧虎", "pos": "名词", "hint": "竹林里刀光剑影的东方武侠", "difficulty": "困难"},
        {"word": "无间", "pos": "名词", "hint": "警匪互卧，天台对峙的港片经典", "difficulty": "困难"},
        {"word": "霸王", "pos": "名词", "hint": "戏里戏外，不疯魔不成活", "difficulty": "困难"},
        {"word": "英雄", "pos": "名词", "hint": "秦箭如雨，一人挡千军的史诗", "difficulty": "困难"},
    ],
    "明星": [
        {"word": "杰伦", "pos": "名词", "hint": "双截棍与晴天的缔造者，华语流行符号", "difficulty": "中等"},
        {"word": "德华", "pos": "名词", "hint": "四大天王之一，常把爱你唱进歌里", "difficulty": "中等"},
        {"word": "星驰", "pos": "名词", "hint": "无厘头喜剧之王，星爷", "difficulty": "中等"},
        {"word": "成龙", "pos": "名词", "hint": "拳脚喜剧，从警察故事打到好莱坞", "difficulty": "简单"},
        {"word": "沈腾", "pos": "名词", "hint": "开心麻花台柱子，西虹市的首富", "difficulty": "简单"},
        {"word": "杨幂", "pos": "名词", "hint": "仙侠剧走出的带货女王", "difficulty": "中等"},
        {"word": "小龙", "pos": "名词", "hint": "截拳道宗师，一声吆喝震碎木板", "difficulty": "中等"},
        {"word": "千玺", "pos": "名词", "hint": "从唱跳少年长成票房担当", "difficulty": "困难"},
    ],
    "网络热词": [
        {"word": "内卷", "pos": "动词", "hint": "跑道上所有人加速，却没人真的往前", "difficulty": "中等"},
        {"word": "破防", "pos": "动词", "hint": "一瞬间，心理防线塌了", "difficulty": "中等"},
        {"word": "躺平", "pos": "动词", "hint": "不卷了，摊着也是一种态度", "difficulty": "中等"},
        {"word": "显眼", "pos": "名词", "hint": "走到哪都要成为目光焦点的人", "difficulty": "中等"},
        {"word": "松弛", "pos": "名词", "hint": "再忙也云淡风轻的气场", "difficulty": "中等"},
        {"word": "雪糕", "pos": "名词", "hint": "其貌不扬，结账时却刺你一刀", "difficulty": "困难"},
        {"word": "班味", "pos": "名词", "hint": "下班也洗不掉的上班族疲惫味", "difficulty": "困难"},
        {"word": "洋气", "pos": "形容词", "hint": "洋不洋气，一句魔性反问走红", "difficulty": "困难"},
    ],
    "日常物品": [
        {"word": "手机", "pos": "名词", "hint": "掌心里连着整个世界的小方块", "difficulty": "简单"},
        {"word": "雨伞", "pos": "名词", "hint": "雨落时撑开，替你挡一片天", "difficulty": "简单"},
        {"word": "充电", "pos": "名词", "hint": "出门在外给手机输血的随身电源", "difficulty": "中等"},
        {"word": "耳机", "pos": "名词", "hint": "塞进耳朵，世界就安静下来的小件", "difficulty": "中等"},
        {"word": "加湿", "pos": "名词", "hint": "干燥季节吐出白雾的小家电", "difficulty": "中等"},
        {"word": "音箱", "pos": "名词", "hint": "不用接线，随处放歌的小方盒", "difficulty": "中等"},
        {"word": "扫地", "pos": "名词", "hint": "圆饼在地上转，自己回家充电", "difficulty": "困难"},
        {"word": "投影", "pos": "名词", "hint": "把电影投上整面墙，替代电视", "difficulty": "困难"},
    ],
    "典故": [
        {"word": "卧薪", "pos": "典故", "hint": "睡柴草尝苦胆，立志复仇的君王", "difficulty": "困难"},
        {"word": "负荆", "pos": "典故", "hint": "赤裸上身背荆条，登门请罪的武将", "difficulty": "困难"},
        {"word": "破釜", "pos": "典故", "hint": "砸锅沉船，断退路决一死战", "difficulty": "困难"},
        {"word": "闻鸡", "pos": "典故", "hint": "鸡鸣即起练剑，惜时如金", "difficulty": "困难"},
        {"word": "画饼", "pos": "典故", "hint": "画个饼哄肚子，空头安慰", "difficulty": "困难"},
        {"word": "望梅", "pos": "典故", "hint": "想想酸梅，干渴就缓解", "difficulty": "困难"},
        {"word": "愚公", "pos": "典故", "hint": "子子孙孙挖山不止的老头", "difficulty": "困难"},
        {"word": "精卫", "pos": "典故", "hint": "衔石填海，小小鸟的不屈", "difficulty": "困难"},
    ],
}
